### PR TITLE
update(todo,pm): small update and fixes.

### PR DESCRIPTION
**Pull request by FedeDP**
Moreover, updated todo.

Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

### CODE REVIEW

**Comment by FedeDP** [comment]
Small changes to your PR ;)

**Comment by tpeacock19** [comment]
I’m not at my computer right now so I can’t point to the exact line, but you’ve removed references to `inh_api` Before the bus call in the two lock functions. These need to be before the call because I’m using the variable to in the callback function. That’s also why inh_api is reset upon a failed call or parse. Unless you have a better solution to the initial dbus call I think we may have to keep it.

**Comment by FedeDP** [comment]
Ops you are right :D I will fix it asap!

**Comment by FedeDP** [comment]
Sorry for the long time no see, but i updated the pr :)

**Pull request merged**
